name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.11.0
  widgetbook_annotation: ^3.3.0
  flutter_riverpod: ^2.6.1
  flutter_starter_kit:
    path: ../
  flex_color_scheme: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  widgetbook_generator: ^3.10.0

flutter:
  uses-material-design: true
